[test]

coverageSkipTestFiles = true       # default false

coverageIgnoreSourcemaps = true   # default false

# to set different thresholds for lines and functions
coverageThreshold = { line = 0.9, function = 0.9 }